adds /api/articles/:article_id endpoint
Deadline76/BE-NC-News pull request #4
Opened 2023-08-15 11:42 UTC by Deadline76

2023-08-15 13:21 UTC, Rayhaan2k9 requested changes
Left some comments for you. As always give me a shout if you need anything clarifying 🙂

2023-08-15 13:21 UTC, Rayhaan2k9 commented on __tests__/app.test.js
> +            delete body.msg.created_at
I see why you have done this, but it is cheating! 😱 The good news is, you don't have to explicitly test the value of ```created_at``` and you can use ```expect.any(String)``` The only explicit value you need to check here is that the ```article_id``` is 1 🙂

2023-08-15 13:21 UTC, Rayhaan2k9 commented on __tests__/app.test.js
> +    })
Great work on error tests! 👏

2023-08-15 13:21 UTC, Rayhaan2k9 commented on app.js
> +    }
This error handler only works because your controller is responding with a custom error with a status of 400. However, we can make this more dynamic. The error will be thrown by psql and we can harness this to create the error handler which will work for other endpoints should the same occur again!

2023-08-15 13:21 UTC, Rayhaan2k9 commented on controllers/controllers.js
> +    .catch(next)
I know this is from a previous ticket, but you don't have to use ```readFile``` here. You can just require the endpoints json file and respond with that 🙂

2023-08-15 13:21 UTC, Rayhaan2k9 commented on controllers/controllers.js
> +    })
This 404 error should ideally be handled in the model if ```rows``` is an empty array. ```Promise.reject()``` will be useful here!

2023-08-15 13:21 UTC, Rayhaan2k9 commented on controllers/controllers.js
> +    })
Let's let psql handle this one. If done correctly, you can just pass ```err``` into ```next``` instead of the full object

2023-08-15 13:21 UTC, Rayhaan2k9 commented on models/models.js
> +
Have a look at my comments in your controller and have a go at implementing it 🙂

2023-08-16 12:26 UTC, leekli approved these changes
Approved.

2023-08-16 12:49 UTC, merged